<?php
$analysis=array(
array("name"=>"思古","url"=>"http://api.bbbbbb.me/jiexi/?url="),
array("name"=>"线路1","url"=>"http://api.nobij.top/jx/?url="),
array("name"=>"强强","url"=>"http://014670.cn/jx/ty.php?url="),
array("name"=>"盘古","url"=>"http://api.pangujiexi.com/player.php?url="),
array("name"=>"新决起TV","url"=>"http://api.zuilingxian.com/jiexi.php?url="),
array("name"=>"七彩云端","url"=>"http://7cyd.com/vip/?url="),
array("name"=>"六六","url"=>"http://qtv.soshane.com/ko.php?url="),
array("name"=>"47KS(AD)","url"=>"http://aty.pw/jx.php?id=1&url=")
)
?>